server{
   listen 80 ;
   server_name 192.168.232.134;
   return 301 https://$host$request-uri;
}
server{
    listen 443 ssl;
    server_name 192.168.232.134;
    ssl_certificate /etc/nginx/ssl/cert.pem;
    ssl_certificate_key  /etc/nginx/ssl/key.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers  HIGH:!aNULL:!MD5;
    add_header Strict-Transport-Security "max-age=3536000" always;
    add_header X-Frame-Options DENY;
    add_header X-Content-Type-Options nosniff; 
    location / {
       proxy_pass     http://poste-mail:80;
       proxy_set_header Host $host;
       proxy_set_header  X-Real-IP $remote_addr;
       proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header  X-Forwarded-Proto $scheme;
    }
}  
